image: docker:stable

variables:
  DEBIAN_FRONTEND: noninteractive
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update
  - apt install -y sudo libtbb-dev cmake-doc cmake autoconf automake libgtest-dev googletest cmake make

services:
  - docker:dind

build_test:
  tags:
    - docker
  stage: build
  image: gcc
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - ctest
